// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LCD_Screen

#ifndef _LCD_SCREEN_UI_H
#define _LCD_SCREEN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Time.h"
#include "ui_Day_Date_Month.h"
#include "ui_Indoor_Weather.h"
#include "ui_Outdoor_Weather.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * RotatingSun_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * rotationtest_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_thermometer_icon_png);    // assets/thermometer_icon.png
LV_IMG_DECLARE(ui_img_indoor_temperature_png);    // assets/indoor_temperature.png
LV_IMG_DECLARE(ui_img_336602858);    // assets/humidity-water-drops-percent-blue-23963.png
LV_IMG_DECLARE(ui_img_sun_png);    // assets/sun.png
LV_IMG_DECLARE(ui_img_497089268);    // assets/full-moon.png
LV_IMG_DECLARE(ui_img_cloud_png);    // assets/cloud.png
LV_IMG_DECLARE(ui_img_storm_png);    // assets/storm.png
LV_IMG_DECLARE(ui_img_fog_png);    // assets/fog.png
LV_IMG_DECLARE(ui_img_cloudynight_png);    // assets/cloudynight.png

// FONTS
LV_FONT_DECLARE(ui_font_Airstrike100);
LV_FONT_DECLARE(ui_font_Chillax100);
LV_FONT_DECLARE(ui_font_Chillax120);
LV_FONT_DECLARE(ui_font_ChillaxReg130);
LV_FONT_DECLARE(ui_font_ChillaxReg70full);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
