// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LCD_Screen

#include "ui.h"

lv_obj_t * ui_OutdoorHumidityIcon;
lv_obj_t * ui_AQI;
lv_obj_t * ui_AQIIcon;
lv_obj_t * ui_OutdoorHumidity;
lv_obj_t * ui_AQIHumidity;
lv_obj_t * ui_AQIHumidity = NULL;
lv_obj_t * ui_OutdoorHumidity = NULL;
lv_obj_t * ui_AQIIcon = NULL;
lv_obj_t * ui_AQI = NULL;
lv_obj_t * ui_OutdoorHumidityIcon = NULL;
// event funtions

// build funtions

void ui_AQIHumidity_screen_init(void)
{
    ui_AQIHumidity = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_AQIHumidity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AQIHumidity, lv_color_hex(0x091425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AQIHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OutdoorHumidity = lv_label_create(ui_AQIHumidity);
    lv_obj_set_width(ui_OutdoorHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OutdoorHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OutdoorHumidity, 92);
    lv_obj_set_y(ui_OutdoorHumidity, 77);
    lv_obj_set_align(ui_OutdoorHumidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OutdoorHumidity, "55");
    lv_obj_set_style_text_color(ui_OutdoorHumidity, lv_color_hex(0xF4EBEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OutdoorHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_OutdoorHumidity, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_OutdoorHumidity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OutdoorHumidity, &ui_font_Jersy, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AQIIcon = lv_image_create(ui_AQIHumidity);
    lv_image_set_src(ui_AQIIcon, &ui_img_390541528);
    lv_obj_set_width(ui_AQIIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AQIIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AQIIcon, -87);
    lv_obj_set_y(ui_AQIIcon, -49);
    lv_obj_set_align(ui_AQIIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AQIIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_AQIIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AQI = lv_label_create(ui_AQIHumidity);
    lv_obj_set_width(ui_AQI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AQI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AQI, -83);
    lv_obj_set_y(ui_AQI, 77);
    lv_obj_set_align(ui_AQI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AQI, "100");
    lv_obj_set_style_text_color(ui_AQI, lv_color_hex(0xF4EBEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AQI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_AQI, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_AQI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AQI, &ui_font_Jersy, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OutdoorHumidityIcon = lv_image_create(ui_AQIHumidity);
    lv_image_set_src(ui_OutdoorHumidityIcon, &ui_img_humidity1_png);
    lv_obj_set_width(ui_OutdoorHumidityIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OutdoorHumidityIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OutdoorHumidityIcon, 87);
    lv_obj_set_y(ui_OutdoorHumidityIcon, -49);
    lv_obj_set_align(ui_OutdoorHumidityIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OutdoorHumidityIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_OutdoorHumidityIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AQIHumidity = ui_AQIHumidity;
    ui_OutdoorHumidity = ui_OutdoorHumidity;
    ui_AQIIcon = ui_AQIIcon;
    ui_AQI = ui_AQI;
    ui_OutdoorHumidityIcon = ui_OutdoorHumidityIcon;

}

void ui_AQIHumidity_screen_destroy(void)
{
    if(ui_AQIHumidity) lv_obj_del(ui_AQIHumidity);

    // NULL screen variables
    ui_AQIHumidity = NULL;
    ui_AQIHumidity = NULL;
    ui_OutdoorHumidity = NULL;
    ui_OutdoorHumidity = NULL;
    ui_AQIIcon = NULL;
    ui_AQIIcon = NULL;
    ui_AQI = NULL;
    ui_AQI = NULL;
    ui_OutdoorHumidityIcon = NULL;
    ui_OutdoorHumidityIcon = NULL;

}
