// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LCD_Screen

#ifndef UI_AQIHUMIDITY_H
#define UI_AQIHUMIDITY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AQIHumidity
extern void ui_AQIHumidity_screen_init(void);
extern void ui_AQIHumidity_screen_destroy(void);
extern lv_obj_t * ui_AQIHumidity;
extern lv_obj_t * ui_OutdoorHumidity;
extern lv_obj_t * ui_AQIIcon;
extern lv_obj_t * ui_AQI;
extern lv_obj_t * ui_OutdoorHumidityIcon;
// CUSTOM VARIABLES
extern lv_obj_t * ui_AQIHumidity;
extern lv_obj_t * ui_OutdoorHumidity;
extern lv_obj_t * ui_AQIIcon;
extern lv_obj_t * ui_AQI;
extern lv_obj_t * ui_OutdoorHumidityIcon;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

