// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LCD_Screen

#include "ui.h"

void ui_comp_Seconds_create_hook(lv_obj_t * comp)
{
}

void ui_comp_thermorot_create_hook(lv_obj_t * comp)
{
}
