// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LCD_Screen

#ifndef _UI_COMP_THERMOROT_H
#define _UI_COMP_THERMOROT_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT thermorot
#define UI_COMP_THERMOROT_THERMOROT 0
#define _UI_COMP_THERMOROT_NUM 1
lv_obj_t * ui_thermorot_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
