// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LCD_Screen

#include "ui.h"

// COMPONENT Seconds

lv_obj_t * ui_Seconds_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Seconds;
    cui_Seconds = lv_spinner_create(comp_parent);
    //lv_spinner_set_anim_params(cui_Seconds, 1000, 90);
    lv_obj_set_width(cui_Seconds, 149);
    lv_obj_set_height(cui_Seconds, 140);
    lv_obj_set_align(cui_Seconds, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Seconds, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_SECONDS_NUM);
    children[UI_COMP_SECONDS_SECONDS] = cui_Seconds;
    lv_obj_add_event_cb(cui_Seconds, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Seconds, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Seconds_create_hook(cui_Seconds);
    return cui_Seconds;
}

