// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LCD_Screen

#ifndef _UI_COMP_SECONDS_H
#define _UI_COMP_SECONDS_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Seconds
#define UI_COMP_SECONDS_SECONDS 0
#define _UI_COMP_SECONDS_NUM 1
lv_obj_t * ui_Seconds_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
