// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LCD_Screen

#include "ui.h"

// COMPONENT thermorot

lv_obj_t * ui_thermorot_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_thermorot;
    cui_thermorot = lv_image_create(comp_parent);
    lv_image_set_src(cui_thermorot, &ui_img_thermometer_icon_png);
    lv_obj_set_width(cui_thermorot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_thermorot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_thermorot, -16);
    lv_obj_set_y(cui_thermorot, 2);
    lv_obj_set_align(cui_thermorot, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_thermorot, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_thermorot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_THERMOROT_NUM);
    children[UI_COMP_THERMOROT_THERMOROT] = cui_thermorot;
    lv_obj_add_event_cb(cui_thermorot, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_thermorot, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_thermorot_create_hook(cui_thermorot);
    return cui_thermorot;
}

