// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LCD_Screen

#ifndef UI_DAY_DATE_MONTH_H
#define UI_DAY_DATE_MONTH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Day_Date_Month
extern void ui_Day_Date_Month_screen_init(void);
extern void ui_Day_Date_Month_screen_destroy(void);
extern lv_obj_t * ui_Day_Date_Month;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_day;
extern lv_obj_t * ui_Month;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Day_Date_Month;
extern lv_obj_t * uic_date;
extern lv_obj_t * uic_day;
extern lv_obj_t * uic_Month;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

