// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LCD_Screen

#ifndef UI_INDOOR_WEATHER_H
#define UI_INDOOR_WEATHER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Indoor_Weather
extern void ui_Indoor_Weather_screen_init(void);
extern void ui_Indoor_Weather_screen_destroy(void);
extern lv_obj_t * ui_Indoor_Weather;
extern lv_obj_t * ui_Full_Temp_Panel;
extern lv_obj_t * ui_temp_icon;
extern lv_obj_t * ui_temp_panel;
extern lv_obj_t * ui_temp;
extern lv_obj_t * ui_dcelcius;
extern lv_obj_t * ui_Temp_Status;
extern lv_obj_t * ui_Header_Panel;
extern lv_obj_t * ui_living_room_icon;
extern lv_obj_t * ui_Living_Room;
extern lv_obj_t * ui_Full_Humidity_Panel;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Humidity_Status;
extern lv_obj_t * ui_temp_panel1;
extern lv_obj_t * ui_Humidity;
extern lv_obj_t * ui_dcelcius1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Indoor_Weather;
extern lv_obj_t * uic_Full_Temp_Panel;
extern lv_obj_t * uic_temp_icon;
extern lv_obj_t * uic_temp_panel;
extern lv_obj_t * uic_temp;
extern lv_obj_t * uic_dcelcius;
extern lv_obj_t * uic_Temp_Status;
extern lv_obj_t * uic_Header_Panel;
extern lv_obj_t * uic_living_room_icon;
extern lv_obj_t * uic_Living_Room;
extern lv_obj_t * uic_Full_Humidity_Panel;
extern lv_obj_t * uic_Humidity_Status;
extern lv_obj_t * uic_Humidity;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

