// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LCD_Screen

#include "ui.h"

lv_obj_t * uic_Humidity;
lv_obj_t * uic_Humidity_Status;
lv_obj_t * uic_Full_Humidity_Panel;
lv_obj_t * uic_Living_Room;
lv_obj_t * uic_living_room_icon;
lv_obj_t * uic_Header_Panel;
lv_obj_t * uic_Temp_Status;
lv_obj_t * uic_dcelcius;
lv_obj_t * uic_temp;
lv_obj_t * uic_temp_panel;
lv_obj_t * uic_temp_icon;
lv_obj_t * uic_Full_Temp_Panel;
lv_obj_t * uic_Indoor_Weather;
lv_obj_t * ui_Indoor_Weather = NULL;
lv_obj_t * ui_Full_Temp_Panel = NULL;
lv_obj_t * ui_temp_icon = NULL;
lv_obj_t * ui_temp_panel = NULL;
lv_obj_t * ui_temp = NULL;
lv_obj_t * ui_dcelcius = NULL;
lv_obj_t * ui_Temp_Status = NULL;
lv_obj_t * ui_Header_Panel = NULL;
lv_obj_t * ui_living_room_icon = NULL;
lv_obj_t * ui_Living_Room = NULL;
lv_obj_t * ui_Full_Humidity_Panel = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Humidity_Status = NULL;
lv_obj_t * ui_temp_panel1 = NULL;
lv_obj_t * ui_Humidity = NULL;
lv_obj_t * ui_dcelcius1 = NULL;
// event funtions

// build funtions

void ui_Indoor_Weather_screen_init(void)
{
    ui_Indoor_Weather = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Indoor_Weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Indoor_Weather, lv_color_hex(0x091425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Indoor_Weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Indoor_Weather, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Indoor_Weather, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Full_Temp_Panel = lv_obj_create(ui_Indoor_Weather);
    lv_obj_set_width(ui_Full_Temp_Panel, 148);
    lv_obj_set_height(ui_Full_Temp_Panel, 180);
    lv_obj_set_x(ui_Full_Temp_Panel, -78);
    lv_obj_set_y(ui_Full_Temp_Panel, 20);
    lv_obj_set_align(ui_Full_Temp_Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Full_Temp_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Full_Temp_Panel, lv_color_hex(0x0C0C0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Full_Temp_Panel, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Full_Temp_Panel, lv_color_hex(0x201F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Full_Temp_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Full_Temp_Panel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Full_Temp_Panel, lv_color_hex(0x403E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Full_Temp_Panel, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Full_Temp_Panel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Full_Temp_Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Full_Temp_Panel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Full_Temp_Panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp_icon = lv_image_create(ui_Full_Temp_Panel);
    lv_image_set_src(ui_temp_icon, &ui_img_thermometer_icon_png);
    lv_obj_set_width(ui_temp_icon, 32);
    lv_obj_set_height(ui_temp_icon, 32);
    lv_obj_set_x(ui_temp_icon, 1);
    lv_obj_set_y(ui_temp_icon, -70);
    lv_obj_set_align(ui_temp_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_temp_icon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_temp_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_temp_icon, LV_IMAGE_ALIGN_STRETCH);
    lv_obj_set_style_radius(ui_temp_icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_temp_icon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_temp_icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp_panel = lv_obj_create(ui_Full_Temp_Panel);
    lv_obj_set_width(ui_temp_panel, 139);
    lv_obj_set_height(ui_temp_panel, 92);
    lv_obj_set_x(ui_temp_panel, 0);
    lv_obj_set_y(ui_temp_panel, 8);
    lv_obj_set_align(ui_temp_panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_temp_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_temp_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_temp_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_temp_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_temp_panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_temp_panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_temp_panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_temp_panel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp = lv_label_create(ui_temp_panel);
    lv_obj_set_width(ui_temp, 127);
    lv_obj_set_height(ui_temp, 89);
    lv_obj_set_x(ui_temp, -12);
    lv_obj_set_y(ui_temp, -5);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp, "88");
    lv_obj_add_flag(ui_temp, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_temp, lv_color_hex(0x269AFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_temp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp, &ui_font_Chillax100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dcelcius = lv_label_create(ui_temp_panel);
    lv_obj_set_width(ui_dcelcius, 28);
    lv_obj_set_height(ui_dcelcius, 25);
    lv_obj_set_x(ui_dcelcius, 58);
    lv_obj_set_y(ui_dcelcius, 15);
    lv_obj_set_align(ui_dcelcius, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_dcelcius, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_dcelcius, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_dcelcius, "°C");
    lv_obj_set_style_text_color(ui_dcelcius, lv_color_hex(0x11EDA8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dcelcius, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dcelcius, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp_Status = lv_label_create(ui_Full_Temp_Panel);
    lv_obj_set_width(ui_Temp_Status, LV_SIZE_CONTENT);   /// 86
    lv_obj_set_height(ui_Temp_Status, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Temp_Status, 0);
    lv_obj_set_y(ui_Temp_Status, 71);
    lv_obj_set_align(ui_Temp_Status, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Temp_Status, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Temp_Status, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_Temp_Status, "Slightly Cool");
    lv_obj_set_style_text_color(ui_Temp_Status, lv_color_hex(0x22E1EC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temp_Status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Temp_Status, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temp_Status, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Header_Panel = lv_obj_create(ui_Indoor_Weather);
    lv_obj_set_width(ui_Header_Panel, 188);
    lv_obj_set_height(ui_Header_Panel, 34);
    lv_obj_set_x(ui_Header_Panel, 0);
    lv_obj_set_y(ui_Header_Panel, -99);
    lv_obj_set_align(ui_Header_Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Header_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Header_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Header_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Header_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Header_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Header_Panel, lv_color_hex(0xDE0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Header_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Header_Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Header_Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Header_Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Header_Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_living_room_icon = lv_image_create(ui_Header_Panel);
    lv_image_set_src(ui_living_room_icon, &ui_img_indoor_temperature_png);
    lv_obj_set_width(ui_living_room_icon, 32);
    lv_obj_set_height(ui_living_room_icon, 32);
    lv_obj_set_x(ui_living_room_icon, -64);
    lv_obj_set_y(ui_living_room_icon, 1);
    lv_obj_set_align(ui_living_room_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_living_room_icon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_living_room_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_living_room_icon, LV_IMAGE_ALIGN_STRETCH);
    lv_obj_set_style_bg_color(ui_living_room_icon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_living_room_icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Living_Room = lv_label_create(ui_Header_Panel);
    lv_obj_set_width(ui_Living_Room, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Living_Room, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Living_Room, 23);
    lv_obj_set_y(ui_Living_Room, 1);
    lv_obj_set_align(ui_Living_Room, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Living_Room, "Living Room");
    lv_obj_set_style_text_color(ui_Living_Room, lv_color_hex(0x17EAE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Living_Room, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Living_Room, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Full_Humidity_Panel = lv_obj_create(ui_Indoor_Weather);
    lv_obj_set_width(ui_Full_Humidity_Panel, 148);
    lv_obj_set_height(ui_Full_Humidity_Panel, 180);
    lv_obj_set_x(ui_Full_Humidity_Panel, 78);
    lv_obj_set_y(ui_Full_Humidity_Panel, 20);
    lv_obj_set_align(ui_Full_Humidity_Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Full_Humidity_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Full_Humidity_Panel, lv_color_hex(0x0C0C0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Full_Humidity_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Full_Humidity_Panel, lv_color_hex(0x201F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Full_Humidity_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Full_Humidity_Panel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Full_Humidity_Panel, lv_color_hex(0x403E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Full_Humidity_Panel, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Full_Humidity_Panel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Full_Humidity_Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Full_Humidity_Panel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Full_Humidity_Panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Full_Humidity_Panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Full_Humidity_Panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Full_Humidity_Panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Full_Humidity_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_Full_Humidity_Panel);
    lv_image_set_src(ui_Image1, &ui_img_336602858);
    lv_obj_set_width(ui_Image1, 32);
    lv_obj_set_height(ui_Image1, 32);
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -70);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_Image1, LV_IMAGE_ALIGN_STRETCH);

    ui_Humidity_Status = lv_label_create(ui_Full_Humidity_Panel);
    lv_obj_set_width(ui_Humidity_Status, 119);
    lv_obj_set_height(ui_Humidity_Status, LV_SIZE_CONTENT);    /// 11
    lv_obj_set_x(ui_Humidity_Status, 1);
    lv_obj_set_y(ui_Humidity_Status, 70);
    lv_obj_set_align(ui_Humidity_Status, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Humidity_Status, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Humidity_Status, "Slightly Humid");
    lv_obj_set_style_text_color(ui_Humidity_Status, lv_color_hex(0x22E1EC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Humidity_Status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Humidity_Status, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humidity_Status, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp_panel1 = lv_obj_create(ui_Full_Humidity_Panel);
    lv_obj_set_width(ui_temp_panel1, 136);
    lv_obj_set_height(ui_temp_panel1, 92);
    lv_obj_set_x(ui_temp_panel1, 0);
    lv_obj_set_y(ui_temp_panel1, 10);
    lv_obj_set_align(ui_temp_panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_temp_panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_temp_panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_temp_panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_temp_panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity = lv_label_create(ui_temp_panel1);
    lv_obj_set_width(ui_Humidity, 127);
    lv_obj_set_height(ui_Humidity, 79);
    lv_obj_set_x(ui_Humidity, -12);
    lv_obj_set_y(ui_Humidity, -5);
    lv_obj_set_align(ui_Humidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humidity, "44");
    lv_obj_add_flag(ui_Humidity, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Humidity, lv_color_hex(0x269AFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Humidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Humidity, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humidity, &ui_font_Chillax100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dcelcius1 = lv_label_create(ui_temp_panel1);
    lv_obj_set_width(ui_dcelcius1, 21);
    lv_obj_set_height(ui_dcelcius1, 25);
    lv_obj_set_x(ui_dcelcius1, 58);
    lv_obj_set_y(ui_dcelcius1, 15);
    lv_obj_set_align(ui_dcelcius1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dcelcius1, "%");
    lv_obj_set_style_text_color(ui_dcelcius1, lv_color_hex(0x11EDA8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dcelcius1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dcelcius1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Indoor_Weather = ui_Indoor_Weather;
    uic_Full_Temp_Panel = ui_Full_Temp_Panel;
    uic_temp_icon = ui_temp_icon;
    uic_temp_panel = ui_temp_panel;
    uic_temp = ui_temp;
    uic_dcelcius = ui_dcelcius;
    uic_Temp_Status = ui_Temp_Status;
    uic_Header_Panel = ui_Header_Panel;
    uic_living_room_icon = ui_living_room_icon;
    uic_Living_Room = ui_Living_Room;
    uic_Full_Humidity_Panel = ui_Full_Humidity_Panel;
    uic_Humidity_Status = ui_Humidity_Status;
    uic_Humidity = ui_Humidity;

}

void ui_Indoor_Weather_screen_destroy(void)
{
    if(ui_Indoor_Weather) lv_obj_del(ui_Indoor_Weather);

    // NULL screen variables
    uic_Indoor_Weather = NULL;
    ui_Indoor_Weather = NULL;
    uic_Full_Temp_Panel = NULL;
    ui_Full_Temp_Panel = NULL;
    uic_temp_icon = NULL;
    ui_temp_icon = NULL;
    uic_temp_panel = NULL;
    ui_temp_panel = NULL;
    uic_temp = NULL;
    ui_temp = NULL;
    uic_dcelcius = NULL;
    ui_dcelcius = NULL;
    uic_Temp_Status = NULL;
    ui_Temp_Status = NULL;
    uic_Header_Panel = NULL;
    ui_Header_Panel = NULL;
    uic_living_room_icon = NULL;
    ui_living_room_icon = NULL;
    uic_Living_Room = NULL;
    ui_Living_Room = NULL;
    uic_Full_Humidity_Panel = NULL;
    ui_Full_Humidity_Panel = NULL;
    ui_Image1 = NULL;
    uic_Humidity_Status = NULL;
    ui_Humidity_Status = NULL;
    ui_temp_panel1 = NULL;
    uic_Humidity = NULL;
    ui_Humidity = NULL;
    ui_dcelcius1 = NULL;

}
