// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LCD_Screen

#ifndef UI_OUTDOOR_WEATHER_H
#define UI_OUTDOOR_WEATHER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Outdoor_Weather
extern void ui_Outdoor_Weather_screen_init(void);
extern void ui_Outdoor_Weather_screen_destroy(void);
extern void ui_event_Outdoor_Weather(lv_event_t * e);
extern lv_obj_t * ui_Outdoor_Weather;
extern void ui_event_SunIcon(lv_event_t * e);
extern lv_obj_t * ui_SunIcon;
extern lv_obj_t * ui_MoonIcon;
extern lv_obj_t * ui_CloudIcon;
extern lv_obj_t * ui_RainIcon;
extern lv_obj_t * ui_FogIcon;
extern lv_obj_t * ui_CloudyNightIcon;
extern lv_obj_t * ui_WeatherDesc;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_OutdoorTemp;
extern lv_obj_t * ui_Celcious;
extern lv_obj_t * ui_OutdoorHumidity;
// CUSTOM VARIABLES
extern lv_obj_t * ui_Outdoor_Weather;
extern lv_obj_t * ui_SunIcon;
extern lv_obj_t * ui_MoonIcon;
extern lv_obj_t * ui_CloudIcon;
extern lv_obj_t * ui_RainIcon;
extern lv_obj_t * ui_CloudyNightIcon;
extern lv_obj_t * ui_WeatherDesc;
extern lv_obj_t * ui_OutdoorTemp;
extern lv_obj_t * ui_Celcious;
extern lv_obj_t * ui_OutdoorHumidity;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

