// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LCD_Screen

#ifndef UI_OUTDOOR_WEATHER_H
#define UI_OUTDOOR_WEATHER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Outdoor_Weather
extern void ui_Outdoor_Weather_screen_init(void);
extern void ui_Outdoor_Weather_screen_destroy(void);
extern lv_obj_t * ui_Outdoor_Weather;
extern lv_obj_t * ui_WeatherAnimIcon;
extern lv_obj_t * ui_OutdoorTemp;
extern lv_obj_t * ui_OutdoorHumidity;
extern lv_obj_t * ui_WeatherDesc;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Outdoor_Weather;
extern lv_obj_t * uic_WeatherAnimIcon;
extern lv_obj_t * uic_OutdoorTemp;
extern lv_obj_t * uic_OutdoorHumidity;
extern lv_obj_t * uic_WeatherDesc;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

