// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LCD_Screen

#include "ui.h"

lv_obj_t * uic_WeatherDesc;
lv_obj_t * uic_OutdoorHumidity;
lv_obj_t * uic_OutdoorTemp;
lv_obj_t * uic_WeatherAnimIcon;
lv_obj_t * uic_Outdoor_Weather;
lv_obj_t * ui_Outdoor_Weather = NULL;
lv_obj_t * ui_WeatherAnimIcon = NULL;
lv_obj_t * ui_OutdoorTemp = NULL;
lv_obj_t * ui_OutdoorHumidity = NULL;
lv_obj_t * ui_WeatherDesc = NULL;
// event funtions

// build funtions

void ui_Outdoor_Weather_screen_init(void)
{
    ui_Outdoor_Weather = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Outdoor_Weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Outdoor_Weather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Outdoor_Weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherAnimIcon = lv_image_create(ui_Outdoor_Weather);
    lv_image_set_src(ui_WeatherAnimIcon, &ui_img_1641329436);
    lv_obj_set_width(ui_WeatherAnimIcon, 120);
    lv_obj_set_height(ui_WeatherAnimIcon, 120);
    lv_obj_set_x(ui_WeatherAnimIcon, -98);
    lv_obj_set_y(ui_WeatherAnimIcon, -61);
    lv_obj_set_align(ui_WeatherAnimIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WeatherAnimIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WeatherAnimIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OutdoorTemp = lv_label_create(ui_Outdoor_Weather);
    lv_obj_set_width(ui_OutdoorTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OutdoorTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OutdoorTemp, 54);
    lv_obj_set_y(ui_OutdoorTemp, -68);
    lv_obj_set_align(ui_OutdoorTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OutdoorTemp, "40");
    lv_obj_set_style_text_font(ui_OutdoorTemp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OutdoorHumidity = lv_label_create(ui_Outdoor_Weather);
    lv_obj_set_width(ui_OutdoorHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OutdoorHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OutdoorHumidity, -63);
    lv_obj_set_y(ui_OutdoorHumidity, 72);
    lv_obj_set_align(ui_OutdoorHumidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OutdoorHumidity, "humidity");
    lv_obj_set_style_text_font(ui_OutdoorHumidity, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherDesc = lv_label_create(ui_Outdoor_Weather);
    lv_obj_set_width(ui_WeatherDesc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherDesc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherDesc, 49);
    lv_obj_set_y(ui_WeatherDesc, -6);
    lv_obj_set_align(ui_WeatherDesc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherDesc, "text");
    lv_obj_set_style_text_font(ui_WeatherDesc, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Outdoor_Weather = ui_Outdoor_Weather;
    uic_WeatherAnimIcon = ui_WeatherAnimIcon;
    uic_OutdoorTemp = ui_OutdoorTemp;
    uic_OutdoorHumidity = ui_OutdoorHumidity;
    uic_WeatherDesc = ui_WeatherDesc;

}

void ui_Outdoor_Weather_screen_destroy(void)
{
    if(ui_Outdoor_Weather) lv_obj_del(ui_Outdoor_Weather);

    // NULL screen variables
    uic_Outdoor_Weather = NULL;
    ui_Outdoor_Weather = NULL;
    uic_WeatherAnimIcon = NULL;
    ui_WeatherAnimIcon = NULL;
    uic_OutdoorTemp = NULL;
    ui_OutdoorTemp = NULL;
    uic_OutdoorHumidity = NULL;
    ui_OutdoorHumidity = NULL;
    uic_WeatherDesc = NULL;
    ui_WeatherDesc = NULL;

}
