// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LCD_Screen

#ifndef UI_TIME_H
#define UI_TIME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Time
extern void ui_Time_screen_init(void);
extern void ui_Time_screen_destroy(void);
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_LabelHour;
extern lv_obj_t * ui_LabelMinutes;
extern lv_obj_t * ui_SecondBar;
extern lv_obj_t * ui_LabelSeconds;
// CUSTOM VARIABLES
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_LabelHour;
extern lv_obj_t * ui_LabelMinutes;
extern lv_obj_t * ui_SecondBar;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

