// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LCD_Screen

#include "ui.h"

lv_obj_t * uic_SecondBar;
lv_obj_t * uic_LabelMinutes;
lv_obj_t * uic_LabelHour;
lv_obj_t * uic_Time;
lv_obj_t * ui_Time = NULL;
lv_obj_t * ui_LabelHour = NULL;
lv_obj_t * ui_LabelMinutes = NULL;
lv_obj_t * ui_SecondBar = NULL;
lv_obj_t * ui_LabelSeconds = NULL;
// event funtions

// build funtions

void ui_Time_screen_init(void)
{
    ui_Time = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Time, lv_color_hex(0x091425), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHour = lv_label_create(ui_Time);
    lv_obj_set_width(ui_LabelHour, 160);
    lv_obj_set_height(ui_LabelHour, 55);
    lv_obj_set_x(ui_LabelHour, -92);
    lv_obj_set_y(ui_LabelHour, -20);
    lv_obj_set_align(ui_LabelHour, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LabelHour, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LabelHour, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LabelHour, "11");
    lv_obj_set_style_text_color(ui_LabelHour, lv_color_hex(0xFF6700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelHour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelHour, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHour, &ui_font_Airstrike100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMinutes = lv_label_create(ui_Time);
    lv_obj_set_width(ui_LabelMinutes, 160);
    lv_obj_set_height(ui_LabelMinutes, 55);
    lv_obj_set_x(ui_LabelMinutes, 73);
    lv_obj_set_y(ui_LabelMinutes, -20);
    lv_obj_set_align(ui_LabelMinutes, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LabelMinutes, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LabelMinutes, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LabelMinutes, "00");
    lv_obj_set_style_text_color(ui_LabelMinutes, lv_color_hex(0xFF6700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMinutes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelMinutes, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMinutes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMinutes, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMinutes, &ui_font_Airstrike100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SecondBar = lv_bar_create(ui_Time);
    lv_bar_set_mode(ui_SecondBar, LV_BAR_MODE_RANGE);
    lv_bar_set_range(ui_SecondBar, 1, 60);
    lv_bar_set_value(ui_SecondBar, 60, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SecondBar, 1, LV_ANIM_OFF);
    lv_obj_set_width(ui_SecondBar, 285);
    lv_obj_set_height(ui_SecondBar, 11);
    lv_obj_set_x(ui_SecondBar, 0);
    lv_obj_set_y(ui_SecondBar, 72);
    lv_obj_set_align(ui_SecondBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SecondBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SecondBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_anim_duration(ui_SecondBar, 500, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SecondBar, lv_color_hex(0xD5B8A1), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SecondBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SecondBar, lv_color_hex(0xFF6700), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SecondBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SecondBar, 128, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SecondBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SecondBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SecondBar,
                                                                                                lv_obj_get_style_pad_right(ui_SecondBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_LabelSeconds = lv_label_create(ui_Time);
    lv_obj_set_width(ui_LabelSeconds, lv_pct(10));
    lv_obj_set_height(ui_LabelSeconds, lv_pct(23));
    lv_obj_set_x(ui_LabelSeconds, lv_pct(-2));
    lv_obj_set_y(ui_LabelSeconds, lv_pct(-11));
    lv_obj_set_align(ui_LabelSeconds, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LabelSeconds, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LabelSeconds, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LabelSeconds, ":");
    lv_obj_set_style_text_color(ui_LabelSeconds, lv_color_hex(0xFF6700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSeconds, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelSeconds, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelSeconds, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSeconds, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSeconds, &ui_font_Airstrike100, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Time = ui_Time;
    uic_LabelHour = ui_LabelHour;
    uic_LabelMinutes = ui_LabelMinutes;
    uic_SecondBar = ui_SecondBar;

}

void ui_Time_screen_destroy(void)
{
    if(ui_Time) lv_obj_del(ui_Time);

    // NULL screen variables
    uic_Time = NULL;
    ui_Time = NULL;
    uic_LabelHour = NULL;
    ui_LabelHour = NULL;
    uic_LabelMinutes = NULL;
    ui_LabelMinutes = NULL;
    uic_SecondBar = NULL;
    ui_SecondBar = NULL;
    ui_LabelSeconds = NULL;

}
