// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LCD_Screen

#include "ui.h"

lv_obj_t * ui_LabelMinutes;
lv_obj_t * ui_LabelHour;
lv_obj_t * ui_Time;
lv_obj_t * ui_Time = NULL;
lv_obj_t * ui_LabelHour = NULL;
lv_obj_t * ui_LabelMinutes = NULL;
lv_obj_t * ui_LabelSeconds = NULL;
// event funtions
void ui_event_Time(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Blink_Animation(ui_LabelSeconds, 50);
    }
}

// build funtions

void ui_Time_screen_init(void)
{
    ui_Time = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Time, lv_color_hex(0x0F0F0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHour = lv_label_create(ui_Time);
    lv_obj_set_width(ui_LabelHour, 146);
    lv_obj_set_height(ui_LabelHour, 158);
    lv_obj_set_x(ui_LabelHour, -86);
    lv_obj_set_y(ui_LabelHour, -6);
    lv_obj_set_align(ui_LabelHour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHour, "11");
    lv_obj_set_style_text_color(ui_LabelHour, lv_color_hex(0xCED0CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelHour, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelHour, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHour, &ui_font_TimeFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMinutes = lv_label_create(ui_Time);
    lv_obj_set_width(ui_LabelMinutes, 148);
    lv_obj_set_height(ui_LabelMinutes, 158);
    lv_obj_set_x(ui_LabelMinutes, 91);
    lv_obj_set_y(ui_LabelMinutes, -6);
    lv_obj_set_align(ui_LabelMinutes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMinutes, "00");
    lv_obj_set_style_text_color(ui_LabelMinutes, lv_color_hex(0xCED0CE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMinutes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelMinutes, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMinutes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMinutes, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMinutes, &ui_font_TimeFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSeconds = lv_label_create(ui_Time);
    lv_obj_set_width(ui_LabelSeconds, 32);
    lv_obj_set_height(ui_LabelSeconds, 141);
    lv_obj_set_x(ui_LabelSeconds, -1);
    lv_obj_set_y(ui_LabelSeconds, -34);
    lv_obj_set_align(ui_LabelSeconds, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSeconds, ":");
    lv_obj_set_style_text_color(ui_LabelSeconds, lv_color_hex(0xE6E8E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSeconds, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelSeconds, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelSeconds, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSeconds, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSeconds, &ui_font_TimeFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Time, ui_event_Time, LV_EVENT_ALL, NULL);
    ui_Time = ui_Time;
    ui_LabelHour = ui_LabelHour;
    ui_LabelMinutes = ui_LabelMinutes;

}

void ui_Time_screen_destroy(void)
{
    if(ui_Time) lv_obj_del(ui_Time);

    // NULL screen variables
    ui_Time = NULL;
    ui_Time = NULL;
    ui_LabelHour = NULL;
    ui_LabelHour = NULL;
    ui_LabelMinutes = NULL;
    ui_LabelMinutes = NULL;
    ui_LabelSeconds = NULL;

}
